routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'guest:admin', 'namespace' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/login', 'LoginController@index')->name('login');
    Route::post('/checklogin', 'LoginController@checklogin')->name('checklogin');

    Route::get('/forgot_password_step-1', 'LoginController@forgotPasswordstep_i_get');
    Route::post('/forgot_password_step-1', 'LoginController@forgotPasswordstep_i')->name('admin-forgot.step-1');
    Route::get('/forgot_password_step-2', 'LoginController@forgotPasswordstep_ii_get');
    Route::get('/forgot_password_step-2/resend_otp', 'LoginController@forgot_resend_otp');
    Route::post('/forgot_password_step-2', 'LoginController@forgotPasswordstep_ii')->name('admin-forgot.step-2');
    Route::get('/otp_verify', 'LoginController@otp_verify_get');
    Route::post('/otp_verify-2', 'LoginController@otp_verify_post')->name('otp-verify');
});

Route::group(['middleware' => 'auth:admin', 'namespace' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/', 'DashboardController@index')->name('home');
    Route::get('/logout', 'LoginController@logout')->name('logout');

    Route::get('/page', 'PageController@index')->name('page.index');
    Route::get('/page/edit/{id}', 'PageController@edit')->name('page.edit');
    Route::post('/page/edit/{id}', 'PageController@update')->name('page.update');

    Route::get('/setting', 'SettingController@edit')->name('setting.edit');
    Route::post('/setting', 'SettingController@update')->name('setting.update');

    Route::get('/change-password', 'LoginController@change_password')->name('user.edit');
    Route::post('/change-password', 'LoginController@save_password')->name('user.update');

    Route::post('/inquery/{id}', 'DashboardController@destroy')->name('inquery_delete');

    Route::get('/plan/{plan}/rule', 'PlanRuleController@index')->name('planrule.index');
    Route::get('/plan/{plan}/ruleadd', 'PlanRuleController@create')->name('planrule.create');
    Route::post('/plan/{plan}/ruleadd', 'PlanRuleController@store')->name('planrule.store');
    Route::get('/plan/{plan}/ruleedit/{id}', 'PlanRuleController@edit')->name('planrule.edit');
    Route::post('/plan/{plan}/ruleedit/{id}', 'PlanRuleController@update')->name('planrule.update');
    Route::post('/plan/ruledelete/{id}', 'PlanRuleController@destroy')->name('planrule.destroy');

    Route::get('/staff/{role}', 'StaffController@index')->name('staff.index');
    Route::get('/staff/{role}/add', 'StaffController@create')->name('staff.create');
    Route::post('/staff/{role}/add', 'StaffController@store')->name('staff.store');
    Route::get('/staff/{role}/verify/{id}', 'StaffController@otp_verify_get')->name('staff.verify');
    Route::post('/staff/{role}/verify/{id}', 'StaffController@otp_verify_post')->name('staff.verify_post');
    Route::get('/staff/{role}/edit/{id}', 'StaffController@edit')->name('staff.edit');
    Route::post('/staff/{role}/edit/{id}', 'StaffController@update')->name('staff.update');
    Route::post('/staff/delete/{id}', 'StaffController@destroy')->name('staff.destroy');
    Route::get('/staff/status/{id}/{status}', 'StaffController@status')->name('staff.status');

    Route::get('/insurance', 'InsuranceController@index')->name('insurance.index');
    Route::get('/insurance/resend_otp', 'InsuranceController@resend_otp');
    Route::get('/insurance/add', 'InsuranceController@create')->name('insurance.create');
    Route::get('/insurance/filter_plan', 'InsuranceController@filter_plan')->name('insurance.filter_plan');    
    Route::get('/insurance/{id}', 'InsuranceController@insurance_detail');
    
    Route::post('/insurance/add', 'InsuranceController@store')->name('insurance.store');
    Route::resources([
        'faq' => 'FaqController',
        'slider' => 'SliderController',
        'brand' => 'BrandController',
        'plan' => 'PlanController',
        'smartphone' => 'MobileController',
        'howitwork' => 'HowitworkController',
        'service' => 'ServiceController',
        'testimonial' => 'TestimonialController',
    ]);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('', 'HomeController@home');
Route::get('contact', 'HomeController@contact');

Route::get('faq', 'HomeController@faq');
Route::get('service', 'HomeController@service');
Route::any('plan', 'PlanController@index')->name('plan');
Route::post('inquery', 'InqueryController@store')->name('inquiry');

Route::get('login', 'AuthController@loginget');
Route::post('login', 'AuthController@loginpost')->name('login');
Route::get('logout', 'AuthController@logout');

Route::get('register', 'AuthController@registerget');
Route::post('register', 'AuthController@registerpost')->name('register');

Route::get('register/otp_verify', 'AuthController@verify_otp');
Route::post('register/otp_verify', 'AuthController@verify_otp_post')->name('otp-verify');
Route::get('register/resend_otp', 'AuthController@resend_otp');

Route::get('profile', 'ProfileController@profile');
Route::post('user-update', 'ProfileController@update')->name('user.update');
Route::post('changepassword', 'ProfileController@changepassword')->name('user.changepassword');
Route::post('service_plan', 'InsuranceController@insurance_re')->name('insurance_re');
Route::get('service_plan/{id}', 'InsuranceController@create')->name('insurance.add');
Route::post('service_plan/{id}', 'InsuranceController@store')->name('insurance.store');
Route::get('page/{slug:slug}', 'HomeController@about');

Route::get('/forgot_password_step-1', 'AuthController@forgotPasswordstep_i_get');
Route::post('/forgot_password_step-1', 'AuthController@forgotPasswordstep_i')->name('forgot.step-1');
Route::get('/forgot_password_step-2', 'AuthController@forgotPasswordstep_ii_get');
Route::post('/forgot_password_step-2', 'AuthController@forgotPasswordstep_ii')->name('forgot.step-2');

app/Http/Controllers/PlanController.php
<?php

namespace App\Http\Controllers;

use App\Model\Plan;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class PlanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $user = $request->user();
        $sess_req = session()->get('sess_req');
        $plan_filter_arr = empty($request->price) && $sess_req ? $sess_req : $request->all();
        
        if($user) {
            $get_price          = (int) $plan_filter_arr['price'];
            $lists  = Plan::with('rule')->where('minprice','<=',$get_price)->where('maxprice','>=',$get_price)->where('active',true)->get();        
            $data   = compact('lists','plan_filter_arr');
            return view('frontend.inc.plan', $data);
        } else {
            session(['sess_req' => $plan_filter_arr]);
            return view('frontend.inc.login');
        }
    }
}

app/Http/Controllers/admin/PlanController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Model\Brand;
use Illuminate\Http\Request;
use App\Model\Plan;
use Illuminate\Support\Str;
use Image;

class PlanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lists = Plan::latest()->paginate(10);

        $data = compact('lists');
        return view('backend.inc.plan.list', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.inc.plan.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'record'        => 'required|array',
            'record.name'   => 'required|string'
        ];

        $messages = [
            'record.name'  => 'Please Enter Name.',
            'image'  => 'Please Select Image'
        ];

        $request->validate($rules, $messages);

        $record           = new Plan;
        $input            = $request->record;

        $record->fill($input);
        if ($record->save()) {
            return redirect(route('admin.plan.index'))->with('success', 'Success! New record has been added.');
        } else {
            return redirect(route('admin.plan.index'))->with('danger', 'Error! Something going wrong.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\planplanplan  $plan
     * @return \Illuminate\Http\Response
     */
    public function show(Plan $plan)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\planplan  $plan
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, Plan $plan)
    {
        $editData =  ['record' => $plan->toArray()];
        $request->replace($editData);
        $request->flash();

        $data = compact('plan');
        return view('backend.inc.plan.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\plan  $plan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Plan $plan)
    {
        $record     = $plan;
        $input      = $request->record;

        $record->fill($input);
        if ($record->save()) {
            return redirect(route('admin.plan.index'))->with('success', 'Success! Record has been edided');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\plan  $plan
     * @return \Illuminate\Http\Response
     */
    public function destroy(Plan $plan)
    {
        $plan->delete();
        return redirect()->back()->with('success', 'Success! Record has been deleted');
    }
}

app/Http/Controllers/api/PlanController.php
<?php
namespace App\Http\Controllers\api;

use Validator;
use Mail;
use Auth;
use DB;
use Intervention\Image\ImageManagerStatic as Image;
use App\Model\Plan;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;

class PlanController extends Controller
{
    public function Plan(Request $request)
    {
        $get_price          = (int) $request['price'];
        $lists  = Plan::with('rule')->where('minprice','<=',$get_price)->where('maxprice','>=',$get_price)->where('active',true)->get();
        
        $re = [
            'status'    => true,
            'message'   => 'total records ' .count($lists),
            'data'      => $lists,
            // 'isExists'  => $user->count()
        ];
        $code = 200;
            
        return response()->json($re, $code);
    }
}

resources/views/backend/inc/plan/_form.blade.php
@if($message = Session::get('error'))
<div class="alert alert-danger alert-block">
  <button type="button" class="close" data-dismiss="alert">x</button>
  {{$message}}
</div>
@endif

@if(count($errors->all()))
<div class="alert alert-danger">
  <ul>
    @foreach($errors->all() as $error)
    <li>{{$error}}</li>
    @endforeach
  </ul>
</div>
@endif
<div class="row">
  <div class="col-lg-4">
    <div class="form-group">
      {{Form::label('name', 'Enter name'), ['class' => 'active']}}
      {{Form::text('record[name]', '', ['class' => 'form-control', 'placeholder'=>'Enter name','required'=>'required'])}}
    </div>
  </div>
  <div class="col-lg-4">
    <div class="form-group">
      {{Form::label('minprice', 'Enter min price'), ['class' => 'active']}}
      {{Form::text('record[minprice]', '', ['class' => 'form-control', 'placeholder'=>'Enter min price'])}}
    </div>
  </div>
  <div class="col-lg-4">
    <div class="form-group">
      {{Form::label('maxprice', 'Enter max price'), ['class' => 'active']}}
      {{Form::text('record[maxprice]', '', ['class' => 'form-control', 'placeholder'=>'Enter max price'])}}
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-6">
    <div class="form-group">
      {{Form::label('price', 'Enter price (per year)'), ['class' => 'active']}}
      {{Form::text('record[price]', '', ['class' => 'form-control', 'placeholder'=>'Enter price'])}}
    </div>
  </div>
  <div class="col-lg-6">
    <div class="form-group">
      {{Form::label('per_month_price', 'Enter price (per month)'), ['class' => 'active']}}
      {{Form::text('record[per_month_price]', '', ['class' => 'form-control', 'placeholder'=>'Enter price'])}}
    </div>
  </div>
</div>

resources/views/backend/inc/plan/add.blade.php
@extends('backend.layout.master')
@section('title','Plan')
@section('content')
<div class="main-content box">
    <main class="main-i">
        <div class="container-fluid">
            <h3 class="mt-4 titl-fo">Add Plan</h3>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item active"><a href="{{ route('admin.home') }}">Dashboard</a></li>
                <li class="breadcrumb-item active"><a href="{{ route('admin.plan.index') }}">Plan</a></li>
                <li class="breadcrumb-item active">Add Plan</li>
            </ol>
            <div class="main-addpage-main">
                <div class="main-form-deco">
                    {{ Form::open(['url' => route('admin.plan.store'), 'method'=>'POST', 'files' => true, 'class' => 'user']) }}
                    @include('backend.inc.plan._form')
                    <div class="text-right mt-4">
                        <input type="submit" class="btn btn-primary" name="save" value="Add" />
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </main>
</div>
@endsection

resources/views/backend/inc/plan/edit.blade.php
@extends('backend.layout.master')
@section('title','Plan Edit')
@section('content')
<div class="main-content box">
    <main class="main-i">
        <div class="container-fluid">
            <h3 class="mt-4 titl-fo">Edit Plan</h3>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item active"><a href="{{ route('admin.home') }}">Dashboard</a></li>
                <li class="breadcrumb-item active"><a href="{{ route('admin.plan.index') }}">Plan</a></li>
                <li class="breadcrumb-item active">Edit Plan</li>
            </ol>
            <div class="main-addpage-main">
                <div class="main-form-deco">
                    {{ Form::open(['url' => route('admin.plan.update',$plan->id), 'method'=>'PUT','files' => true, 'class' => 'user']) }}
                    @include('backend.inc.plan._form')
                    <div class="text-right">
                        <input type="submit" class="btn btn-primary" name="edit_plan" value="Update" />
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </main>
</div>
@endsection

resources/views/backend/inc/plan/list.blade.php
@extends('backend.layout.master')
@section('title','Plan')
@section('content')
<div class="main-content box">
    <main class="main-i">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6">
                    <h3 class="mt-4 titl-fo">View Plan</h3>
                    <ol class="breadcrumb mb-4">
                        <li class="breadcrumb-item active"><a href="{{ route('admin.home') }}">Dashboard</a></li>
                        <li class="breadcrumb-item active">Plan</li>
                    </ol>
                </div>
                <div class="col-lg-6">
                    <div class="buton-add-new">
                        <a href="{{ route('admin.plan.create') }}" class="btn btn-primary" type="button"><i class='bx bx-plus'>Add</i></a>
                    </div>
                </div>
            </div>
            <section class="recent">
                <div class="activiti-card">
                    <!-- <div class="search-top-table">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="searchbarleft">
                                    <input type="text" class="search-input-table" name="Search" placeholder="Search-Filter">
                                </div>
                                <h4>View plan</h4>
                            </div>
                            <div class="col-lg-6">
                                <div class="table-head-right">
                                    <button type="button"><i class='bx bxs-trash'></i></button>
                                </div>
                            </div>
                        </div>
                    </div> -->
                    <div class="table-responsiveima pt-4">
                    <input class="form-control mb-3" style="width:25%" id="myInput" type="text" placeholder="Search..">
                        <table>
                            <thead class="the-colo-table">
                                <tr>
                                    <!-- <th><input type="checkbox" name="sr.no">Sr.No</th> -->
                                    <th>S. No.</th>
                                    <th>Name</th>
                                    <th>Min Price</th>
                                    <th>Max Price</th>
                                    <th>Price (per year)</th>
                                    <th>Price (per month)</th>
                                    <th>Action</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody id="myTable">
                                @php
                                $sn = 1;
                                @endphp
                                @foreach($lists as $list)
                                <tr>
                                    <td>{{ $sn++ }}</td>
                                    <td>
                                        <a href="{{ route('admin.plan.edit',$list->id) }}"><i class=" bx bxs-edit"></i> {{ $list->name }}</a>
                                    </td>
                                    <td>₹{{ $list->minprice }} </td>
                                    <td>₹{{ $list->maxprice }} </td>
                                    <td>₹{{ $list->price }} </td>
                                    <td>₹{{ $list->per_month_price }} </td>
                                    <td>
                                        <!-- <button class="btn tblActnBtn p-0">
                                            <a href="{{ route('admin.plan.edit',$list->id) }}" style="color: black;"><i class="bx bxs-edit"></i></a>
                                        </button> -->
                                        {{ Form::open(array('url' => route('admin.plan.destroy',$list->id), 'class' => 'btn tblActnBtn','style'=> 'padding:0px;')) }}
                                        {{ Form::hidden('_method', 'DELETE') }}
                                        <button class="btn tblActnBtn">
                                            <a style="color: black;"><i class="bx bxs-trash"></i></a>
                                        </button>
                                        {{ Form::close() }}
                                    </td>
                                    <td>
                                        <button class="btn tblActnBtn p-0">
                                            <a href="{{ route('admin.planrule.index',$list->id) }}"><i class="bx bxs-eye"></i> View Rules</a>
                                        </button>
                                    </td>

                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        
                    </div>
                    <div class="p-3 text-right">{{ $lists->links() }}</div>
                </div>
            </section>
        </div>
    </main>
</div>
@endsection