routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'guest:admin', 'namespace' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/login', 'LoginController@index')->name('login');
    Route::post('/checklogin', 'LoginController@checklogin')->name('checklogin');

    Route::get('/forgot_password_step-1', 'LoginController@forgotPasswordstep_i_get');
    Route::post('/forgot_password_step-1', 'LoginController@forgotPasswordstep_i')->name('admin-forgot.step-1');
    Route::get('/forgot_password_step-2', 'LoginController@forgotPasswordstep_ii_get');
    Route::get('/forgot_password_step-2/resend_otp', 'LoginController@forgot_resend_otp');
    Route::post('/forgot_password_step-2', 'LoginController@forgotPasswordstep_ii')->name('admin-forgot.step-2');
    Route::get('/otp_verify', 'LoginController@otp_verify_get');
    Route::post('/otp_verify-2', 'LoginController@otp_verify_post')->name('otp-verify');
});

Route::group(['middleware' => 'auth:admin', 'namespace' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/', 'DashboardController@index')->name('home');
    Route::get('/logout', 'LoginController@logout')->name('logout');

    Route::get('/page', 'PageController@index')->name('page.index');
    Route::get('/page/edit/{id}', 'PageController@edit')->name('page.edit');
    Route::post('/page/edit/{id}', 'PageController@update')->name('page.update');

    Route::get('/setting', 'SettingController@edit')->name('setting.edit');
    Route::post('/setting', 'SettingController@update')->name('setting.update');

    Route::get('/change-password', 'LoginController@change_password')->name('user.edit');
    Route::post('/change-password', 'LoginController@save_password')->name('user.update');

    Route::post('/inquery/{id}', 'DashboardController@destroy')->name('inquery_delete');

    Route::get('/plan/{plan}/rule', 'PlanRuleController@index')->name('planrule.index');
    Route::get('/plan/{plan}/ruleadd', 'PlanRuleController@create')->name('planrule.create');
    Route::post('/plan/{plan}/ruleadd', 'PlanRuleController@store')->name('planrule.store');
    Route::get('/plan/{plan}/ruleedit/{id}', 'PlanRuleController@edit')->name('planrule.edit');
    Route::post('/plan/{plan}/ruleedit/{id}', 'PlanRuleController@update')->name('planrule.update');
    Route::post('/plan/ruledelete/{id}', 'PlanRuleController@destroy')->name('planrule.destroy');

    Route::get('/staff/{role}', 'StaffController@index')->name('staff.index');
    Route::get('/staff/{role}/add', 'StaffController@create')->name('staff.create');
    Route::post('/staff/{role}/add', 'StaffController@store')->name('staff.store');
    Route::get('/staff/{role}/verify/{id}', 'StaffController@otp_verify_get')->name('staff.verify');
    Route::post('/staff/{role}/verify/{id}', 'StaffController@otp_verify_post')->name('staff.verify_post');
    Route::get('/staff/{role}/edit/{id}', 'StaffController@edit')->name('staff.edit');
    Route::post('/staff/{role}/edit/{id}', 'StaffController@update')->name('staff.update');
    Route::post('/staff/delete/{id}', 'StaffController@destroy')->name('staff.destroy');
    Route::get('/staff/status/{id}/{status}', 'StaffController@status')->name('staff.status');

    Route::get('/insurance', 'InsuranceController@index')->name('insurance.index');
    Route::get('/insurance/resend_otp', 'InsuranceController@resend_otp');
    Route::get('/insurance/add', 'InsuranceController@create')->name('insurance.create');
    Route::get('/insurance/filter_plan', 'InsuranceController@filter_plan')->name('insurance.filter_plan');    
    Route::get('/insurance/{id}', 'InsuranceController@insurance_detail');
    
    Route::post('/insurance/add', 'InsuranceController@store')->name('insurance.store');
    Route::resources([
        'faq' => 'FaqController',
        'slider' => 'SliderController',
        'brand' => 'BrandController',
        'plan' => 'PlanController',
        'smartphone' => 'MobileController',
        'howitwork' => 'HowitworkController',
        'service' => 'ServiceController',
        'testimonial' => 'TestimonialController',
    ]);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('', 'HomeController@home');
Route::get('contact', 'HomeController@contact');

Route::get('faq', 'HomeController@faq');
Route::get('service', 'HomeController@service');
Route::any('plan', 'PlanController@index')->name('plan');
Route::post('inquery', 'InqueryController@store')->name('inquiry');

Route::get('login', 'AuthController@loginget');
Route::post('login', 'AuthController@loginpost')->name('login');
Route::get('logout', 'AuthController@logout');

Route::get('register', 'AuthController@registerget');
Route::post('register', 'AuthController@registerpost')->name('register');

Route::get('register/otp_verify', 'AuthController@verify_otp');
Route::post('register/otp_verify', 'AuthController@verify_otp_post')->name('otp-verify');
Route::get('register/resend_otp', 'AuthController@resend_otp');

Route::get('profile', 'ProfileController@profile');
Route::post('user-update', 'ProfileController@update')->name('user.update');
Route::post('changepassword', 'ProfileController@changepassword')->name('user.changepassword');
Route::post('service_plan', 'InsuranceController@insurance_re')->name('insurance_re');
Route::get('service_plan/{id}', 'InsuranceController@create')->name('insurance.add');
Route::post('service_plan/{id}', 'InsuranceController@store')->name('insurance.store');
Route::get('page/{slug:slug}', 'HomeController@about');

Route::get('/forgot_password_step-1', 'AuthController@forgotPasswordstep_i_get');
Route::post('/forgot_password_step-1', 'AuthController@forgotPasswordstep_i')->name('forgot.step-1');
Route::get('/forgot_password_step-2', 'AuthController@forgotPasswordstep_ii_get');
Route::post('/forgot_password_step-2', 'AuthController@forgotPasswordstep_ii')->name('forgot.step-2');

app/Http/Controllers/admin/SettingController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Setting;
use Illuminate\Support\Str;
use Image;

class SettingController extends Controller
{
    public function edit(Request $request, Setting $setting)
    {
        $setting = Setting::find(1);
        $editData =  ['record' => $setting->toArray()];
        $request->replace($editData);
        $request->flash();

        $data = compact('setting');
        return view('backend.inc.setting.edit', $data);
    }


    public function update(Request $request, Setting $setting)
    {
        $record     = Setting::find(1);
        $input      = $request->record;
        if ($request->hasFile('logo')) {
            $file = $request->logo;
            $optimizeImage = Image::make($file);
            $optimizePath = public_path() . '/images/setting/logo/';
            $name = 'logo.png';
            $optimizeImage->save($optimizePath . $name, 72);
            $input['logo'] = $name;
        }
        if ($request->hasFile('favicon')) {
            $file = $request->favicon;
            $optimizeImage = Image::make($file);
            $optimizeImage->resize(70, 70);
            $optimizePath = public_path() . '/images/setting/favicon/';
            $name = 'favicon.png';
            $optimizeImage->save($optimizePath . $name, 72);
            $input['favicon'] = $name;
        }

        $record->fill($input);
        if ($record->save()) {
            return redirect(route('admin.setting.edit', $setting->id))->with('success', 'Success! Record has been edided');
        }
    }
}

app/Http/Controllers/api/SettingController.php
<?php
namespace App\Http\Controllers\api;

use Validator;
use Mail;
use Auth;
use DB;
use Intervention\Image\ImageManagerStatic as Image;
use App\Model\Setting;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;

class SettingController extends Controller
{
    public function get_setting(Request $request)
    {
        $Data  = DB::table('settings')->find(1);
        
        foreach($Data as $index => $arr){
                
                // foreach($arr as $key => $value){
                    
                    if($arr == null){
                        
                     $Data->{$index}= ''; 
                    }
                // }
            }
        
        $re = [
            'status'    => true,
            'message'   => 'Success',
            'data'      => $Data,
        ];
        $code = 200;
            
        return response()->json($re, $code);
    }
    
    public function edit_setting(Request $request)
    {
       $validator = Validator::make($request->all(), [
            'title'     => 'required',
        ]);
        if ($validator->fails()) {
            $re = [
                'status'    => false,
                'message'   => 'Validations errors found.',
                'errors'    => $validator->errors()
            ];
            $code = 401;
        } else {
            $record     = Setting::find(1);
            $input      = $request->all();
            if ($request->hasFile('logo')) {
                $file = $request->logo;
                $optimizeImage = Image::make($file);
                $optimizePath = public_path() . '/images/setting/logo/';
                $name = 'logo.png';
                $optimizeImage->save($optimizePath . $name, 72);
                $input['logo'] = $name;
            }
            if ($request->hasFile('favicon')) {
                $file = $request->favicon;
                $optimizeImage = Image::make($file);
                $optimizeImage->resize(70, 70);
                $optimizePath = public_path() . '/images/setting/favicon/';
                $name = 'favicon.png';
                $optimizeImage->save($optimizePath . $name, 72);
                $input['favicon'] = $name;
            }
    
            $record->fill($input);
            if ($record->save()) {
                $re = [
                    'status'    => true,
                    'message'   => 'Success.'
                ];
                $code = 200;
            }
        }
        return response()->json($re, $code);
    }
}

resources/views/backend/inc/setting/_form.blade.php
@if($message = Session::get('error'))
<div class="alert alert-danger alert-block">
  <button type="button" class="close" data-dismiss="alert">x</button>
  {{$message}}
</div>
@endif

@if(count($errors->all()))
<div class="alert alert-danger">
  <ul>
    @foreach($errors->all() as $error)
    <li>{{$error}}</li>
    @endforeach
  </ul>
</div>
@endif
<div class="row">
  <div class="col-lg-6">
    <div class="form-group">
      {{Form::label('title', 'Enter name'), ['class' => 'active']}}
      {{Form::text('record[title]', '', ['class' => 'form-control', 'placeholder'=>'Enter name','required'=>'required'])}}
    </div>
  </div>
  <div class="col-lg-6">
    <div class="row">
      <div class="col-lg-6">
        <div class="form-group">
          {{Form::label('logo', 'Choose logo'), ['class' => 'active']}}
          {{Form::file('logo',['class'=>'form-control'])}}
        </div>
      </div>
      <div class="col-lg-6">
        <div class="form-group">
          @if($setting->logo)
          <img src="{{ url('/images/setting/logo/'.$setting->logo) }}" width="50%">
          @endif
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="form-group">
      {{Form::label('tagline', 'Enter tagline'), ['class' => 'active']}}
      {{Form::text('record[tagline]', '', ['class' => 'form-control', 'placeholder'=>'Enter tagline'])}}
    </div>
  </div>
  <div class="col-lg-6">
    <div class="row">
      <div class="col-lg-6">
        <div class="form-group">
          {{Form::label('favicon', 'Choose favicon'), ['class' => 'active']}}
          {{Form::file('favicon',['class'=>'form-control'])}}
        </div>
      </div>
      <div class="col-lg-6">
        <div class="form-group">
          @if($setting->favicon)
          <img src="{{ url('/images/setting/favicon/'.$setting->favicon) }}" width="30%">
          @endif
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="form-group">
      {{Form::label('mobile', 'Enter mobile'), ['class' => 'active']}}
      {{Form::text('record[mobile]', '', ['class' => 'form-control', 'placeholder'=>'Enter mobile','required'=>'required'])}}
    </div>
  </div>
  <div class="col-lg-6">
    <div class="form-group">
      {{Form::label('email', 'Enter email'), ['class' => 'active']}}
      {{Form::text('record[email]', '', ['class' => 'form-control', 'placeholder'=>'Enter email','required'=>'required'])}}
    </div>
  </div>
  <div class="col-lg-6">
    <div class="form-group">
      {{ Form::label('address', 'Enter address'), ['class' => 'active'] }}
      {{ Form::textarea('record[address]','', ['class'=>'form-control', 'placeholder'=>'Enter address', 'rows' => '5', 'cols' => '10']) }}
    </div>
  </div>
  <div class="col-lg-6">
    <div class="form-group">
      {{Form::label('facebook', 'Enter facebook url'), ['class' => 'active']}}
      {{Form::text('record[facebook]', '', ['class' => 'form-control', 'placeholder'=>'Enter facebook url'])}}
    </div>
  </div>
  <div class="col-lg-6">
    <div class="form-group">
      {{Form::label('instagram', 'Enter instagram url'), ['class' => 'active']}}
      {{Form::text('record[instagram]', '', ['class' => 'form-control', 'placeholder'=>'Enter instagram url'])}}
    </div>
  </div>
  <div class="col-lg-6">
    <div class="form-group">
      {{Form::label('twitter', 'Enter twitter url'), ['class' => 'active']}}
      {{Form::text('record[twitter]', '', ['class' => 'form-control', 'placeholder'=>'Enter twitter url'])}}
    </div>
  </div>
  <div class="col-lg-6">
    <div class="form-group">
      {{Form::label('pintertest', 'Enter pintertest url'), ['class' => 'active']}}
      {{Form::text('record[pintertest]', '', ['class' => 'form-control', 'placeholder'=>'Enter pintertest url'])}}
    </div>
  </div>
  <div class="col-lg-6">
    <div class="form-group">
      {{Form::label('youtube', 'Enter youtube url'), ['class' => 'active']}}
      {{Form::text('record[youtube]', '', ['class' => 'form-control', 'placeholder'=>'Enter youtube url'])}}
    </div>
  </div>
  <div class="col-lg-6">
    <div class="form-group">
      {{Form::label('bank_name', 'Enter bank name'), ['class' => 'active']}}
      {{Form::text('record[bank_name]', '', ['class' => 'form-control', 'placeholder'=>'Enter bank name'])}}
    </div>
  </div>
  <div class="col-lg-6">
    <div class="form-group">
      {{Form::label('branch_name', 'Enter branch name'), ['class' => 'active']}}
      {{Form::text('record[branch_name]', '', ['class' => 'form-control', 'placeholder'=>'Enter branch name'])}}
    </div>
  </div>
  <div class="col-lg-6">
    <div class="form-group">
      {{Form::label('bank_ac', 'Enter bank A/C'), ['class' => 'active']}}
      {{Form::text('record[bank_ac]', '', ['class' => 'form-control', 'placeholder'=>'Enter bank A/C'])}}
    </div>
  </div>
  <div class="col-lg-6">
    <div class="form-group">
      {{Form::label('bank_ifsc', 'Enter bank ifsc'), ['class' => 'active']}}
      {{Form::text('record[bank_ifsc]', '', ['class' => 'form-control', 'placeholder'=>'Enter bank ifsc'])}}
    </div>
  </div>
  <div class="col-lg-6">
    <div class="form-group">
      {{Form::label('GST', 'Enter GST'), ['class' => 'active']}}
      {{Form::text('record[GST]', '', ['class' => 'form-control', 'placeholder'=>'Enter GST'])}}
    </div>
  </div>
  <div class="col-lg-12">
    <div class="form-group">
      {{ Form::label('invoice_terms', 'Enter invoice terms'), ['class' => 'active'] }}
      {{ Form::textarea('record[invoice_terms]','', ['class'=>'form-control editor', 'id'=> '', 'placeholder'=>'Enter invoice terms']) }}
    </div>
  </div>

</div>

resources/views/backend/inc/setting/edit.blade.php
@extends('backend.layout.master')
@section('title','Setting Edit')
@section('content')
<div class="main-content box">
    <main class="main-i">
        <div class="container-fluid">
            <h3 class="mt-4 titl-fo">Setting</h3>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item active"><a href="{{ route('admin.home') }}">Dashboard</a></li>
                <li class="breadcrumb-item active">Setting</li>
            </ol>
            <div class="main-addpage-main">
                <div class="main-form-deco">
                    {{ Form::open(['url' => route('admin.setting.update',$setting->id), 'method'=>'POST','files' => true, 'class' => 'user']) }}
                    @include('backend.inc.setting._form')
                    <div class="text-right">
                        <input type="submit" class="btn btn-primary" name="edit_setting" value="Update" />
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </main>
</div>
@endsection