routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'guest:admin', 'namespace' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/login', 'LoginController@index')->name('login');
    Route::post('/checklogin', 'LoginController@checklogin')->name('checklogin');

    Route::get('/forgot_password_step-1', 'LoginController@forgotPasswordstep_i_get');
    Route::post('/forgot_password_step-1', 'LoginController@forgotPasswordstep_i')->name('admin-forgot.step-1');
    Route::get('/forgot_password_step-2', 'LoginController@forgotPasswordstep_ii_get');
    Route::get('/forgot_password_step-2/resend_otp', 'LoginController@forgot_resend_otp');
    Route::post('/forgot_password_step-2', 'LoginController@forgotPasswordstep_ii')->name('admin-forgot.step-2');
    Route::get('/otp_verify', 'LoginController@otp_verify_get');
    Route::post('/otp_verify-2', 'LoginController@otp_verify_post')->name('otp-verify');
});

Route::group(['middleware' => 'auth:admin', 'namespace' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/', 'DashboardController@index')->name('home');
    Route::get('/logout', 'LoginController@logout')->name('logout');

    Route::get('/page', 'PageController@index')->name('page.index');
    Route::get('/page/edit/{id}', 'PageController@edit')->name('page.edit');
    Route::post('/page/edit/{id}', 'PageController@update')->name('page.update');

    Route::get('/setting', 'SettingController@edit')->name('setting.edit');
    Route::post('/setting', 'SettingController@update')->name('setting.update');

    Route::get('/change-password', 'LoginController@change_password')->name('user.edit');
    Route::post('/change-password', 'LoginController@save_password')->name('user.update');

    Route::post('/inquery/{id}', 'DashboardController@destroy')->name('inquery_delete');

    Route::get('/plan/{plan}/rule', 'PlanRuleController@index')->name('planrule.index');
    Route::get('/plan/{plan}/ruleadd', 'PlanRuleController@create')->name('planrule.create');
    Route::post('/plan/{plan}/ruleadd', 'PlanRuleController@store')->name('planrule.store');
    Route::get('/plan/{plan}/ruleedit/{id}', 'PlanRuleController@edit')->name('planrule.edit');
    Route::post('/plan/{plan}/ruleedit/{id}', 'PlanRuleController@update')->name('planrule.update');
    Route::post('/plan/ruledelete/{id}', 'PlanRuleController@destroy')->name('planrule.destroy');

    Route::get('/staff/{role}', 'StaffController@index')->name('staff.index');
    Route::get('/staff/{role}/add', 'StaffController@create')->name('staff.create');
    Route::post('/staff/{role}/add', 'StaffController@store')->name('staff.store');
    Route::get('/staff/{role}/verify/{id}', 'StaffController@otp_verify_get')->name('staff.verify');
    Route::post('/staff/{role}/verify/{id}', 'StaffController@otp_verify_post')->name('staff.verify_post');
    Route::get('/staff/{role}/edit/{id}', 'StaffController@edit')->name('staff.edit');
    Route::post('/staff/{role}/edit/{id}', 'StaffController@update')->name('staff.update');
    Route::post('/staff/delete/{id}', 'StaffController@destroy')->name('staff.destroy');
    Route::get('/staff/status/{id}/{status}', 'StaffController@status')->name('staff.status');

    Route::get('/insurance', 'InsuranceController@index')->name('insurance.index');
    Route::get('/insurance/resend_otp', 'InsuranceController@resend_otp');
    Route::get('/insurance/add', 'InsuranceController@create')->name('insurance.create');
    Route::get('/insurance/filter_plan', 'InsuranceController@filter_plan')->name('insurance.filter_plan');    
    Route::get('/insurance/{id}', 'InsuranceController@insurance_detail');
    
    Route::post('/insurance/add', 'InsuranceController@store')->name('insurance.store');
    Route::resources([
        'faq' => 'FaqController',
        'slider' => 'SliderController',
        'brand' => 'BrandController',
        'plan' => 'PlanController',
        'smartphone' => 'MobileController',
        'howitwork' => 'HowitworkController',
        'service' => 'ServiceController',
        'testimonial' => 'TestimonialController',
    ]);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('', 'HomeController@home');
Route::get('contact', 'HomeController@contact');

Route::get('faq', 'HomeController@faq');
Route::get('service', 'HomeController@service');
Route::any('plan', 'PlanController@index')->name('plan');
Route::post('inquery', 'InqueryController@store')->name('inquiry');

Route::get('login', 'AuthController@loginget');
Route::post('login', 'AuthController@loginpost')->name('login');
Route::get('logout', 'AuthController@logout');

Route::get('register', 'AuthController@registerget');
Route::post('register', 'AuthController@registerpost')->name('register');

Route::get('register/otp_verify', 'AuthController@verify_otp');
Route::post('register/otp_verify', 'AuthController@verify_otp_post')->name('otp-verify');
Route::get('register/resend_otp', 'AuthController@resend_otp');

Route::get('profile', 'ProfileController@profile');
Route::post('user-update', 'ProfileController@update')->name('user.update');
Route::post('changepassword', 'ProfileController@changepassword')->name('user.changepassword');
Route::post('service_plan', 'InsuranceController@insurance_re')->name('insurance_re');
Route::get('service_plan/{id}', 'InsuranceController@create')->name('insurance.add');
Route::post('service_plan/{id}', 'InsuranceController@store')->name('insurance.store');
Route::get('page/{slug:slug}', 'HomeController@about');

Route::get('/forgot_password_step-1', 'AuthController@forgotPasswordstep_i_get');
Route::post('/forgot_password_step-1', 'AuthController@forgotPasswordstep_i')->name('forgot.step-1');
Route::get('/forgot_password_step-2', 'AuthController@forgotPasswordstep_ii_get');
Route::post('/forgot_password_step-2', 'AuthController@forgotPasswordstep_ii')->name('forgot.step-2');

app/Http/Controllers/admin/StaffController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Model\Admin;
use Illuminate\Http\Request;
use App\Model\PlanCondition;
use App\Model\Role;
use App\Model\Setting;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Image;

class StaffController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($role)
    {
        $check = Role::where('name', $role)->count();
        
        if ($check != 0) {

            $query = Admin::whereHas('role', function ($q) use ($role) {
                $q->where('name', $role)->with('admin','role');
            });
            if (auth()->user()->role_id == 2 ) {
                if($role == 'Shop'){
                    $staff = Admin::where('admin_id',auth()->user()->id)->where('role_id',5)->get();
                    // dd($staff);
                    $staff_arr = [];
                    foreach($staff as $s){
                        $staff_arr[] = $s->id;                        
                    }
                    // $staff_arr = 29,35;
                    // dd($staff_arr);                    
                    $staff_arr[] = auth()->user()->id;                   
                    
                    $query->whereIn('admin_id', $staff_arr);
                    
                    
                }
                if($role == 'Staff'){
                    $query->where('admin_id', auth()->user()->id);
                }

            }

            if (auth()->user()->role_id == 5 ) {
                $query->where('admin_id', auth()->user()->id);
            }
            $lists = $query->paginate(10);

            $data = compact('lists', 'role');
            return view('backend.inc.staff.list', $data);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($role)
    {
        $data = compact('role');
        return view('backend.inc.staff.add', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $role)
    {
        
        $rules = [
            'record'        => 'required|array',
            'record.fname'   => 'required|string',
            'record.mobile'  => 'required|unique:admins,mobile'
        ];

        $messages = [
            'record.name'  => 'Please Enter Name.',
            'image'  => 'Please Select Image'
        ];
        

        $roleid = Role::where('name', $role)->first();

        $request->validate($rules, $messages);

        $record           = new Admin;
        $input            = $request->record;
        $input['password']    = Hash::make($input['password']);
        $input['role_id']    = $roleid->id;
        $input['admin_id'] = auth()->user()->id;

        if ($request->hasFile('aadhar_front')) {
            $file = $request->aadhar_front;
            $optimizeImage = Image::make($file);
            // $optimizeImage->resize(1903, 523);
            $optimizePath = public_path() . '/images/admin/aadhar/';
            $name = time() . $file->getClientOriginalName();
            $optimizeImage->save($optimizePath . $name, 72);
            $input['aadhar_front'] = $name;
        }
        if ($request->hasFile('aadhar_back')) {
            $file = $request->aadhar_back;
            $optimizeImage = Image::make($file);
            // $optimizeImage->resize(1903, 523);
            $optimizePath = public_path() . '/images/admin/aadhar/';
            $name = time() . $file->getClientOriginalName();
            $optimizeImage->save($optimizePath . $name, 72);
            $input['aadhar_back'] = $name;
        }
        if ($request->hasFile('pan_img')) {
            $file = $request->pan_img;
            $optimizeImage = Image::make($file);
            // $optimizeImage->resize(1903, 523);
            $optimizePath = public_path() . '/images/admin/pan_card/';
            $name = time() . $file->getClientOriginalName();
            $optimizeImage->save($optimizePath . $name, 72);
            $input['pan_img'] = $name;
        }
        if ($request->hasFile('bank_statement')) {
            $file = $request->bank_statement;
            $optimizeImage = Image::make($file);
            // $optimizeImage->resize(1903, 523);
            $optimizePath = public_path() . '/images/admin/bank_statement/';
            $name = time() . $file->getClientOriginalName();
            $optimizeImage->save($optimizePath . $name, 72);
            $input['bank_statement'] = $name;
        }
        // $setting = Setting::find(1);
        // $otp = rand(100000,999999);
        // $input['otp_code']=$otp;
		$input['is_otp_verified']= '0';
		
		// $msg = urlencode("Dear ".$setting->title." user, ".$otp." is the OTP for your mobile number verification. PLS DO NOT SHARE WITH ANYONE. Regards APR SERVICES");
        // // dd($msg);
        // $apiUrl = str_replace(["[MOBILE]", "[MESSAGE]"], [$input['mobile'],$msg], $setting->sms_api);

        // // dd($apiUrl);
        // $sms    = file_get_contents($apiUrl);
        // $record->fill($input);
        // if ($record->save()) {
            
        //     return redirect(route('admin.staff.verify',[$role, $record->id]))->with('success', 'Success! New record has been added.');
        // } else {
        //     return redirect(route('admin.staff.index', $role))->with('danger', 'Error! Something going wrong.');
        // }
        $record->fill($input);
        if ($record->save()) {
            return redirect(route('admin.staff.index', $role))->with('success', 'Success! New record has been added.');
        }
    }
    public function otp_verify_get($role,$id)
    {
        
        $user = Admin::find($id);

        $data = compact('user','role','id');
        return view('backend.inc.staff.otp_verify', $data);
        
    }
    public function otp_verify_post(Request $request, $role, $id)
    {
        // dd($id);
        // dd($role);
        $rules = [
            'record'        => 'required|array',
            'record.otp_code'   => 'required'
        ];

        $messages = [
            'otp_code'  => 'Please Enter OTP.',
        ];

        $request->validate($rules, $messages);
        $input  = $request->record;
        // dd($input['otp_code']);
        $user = Admin::where('id',$id)->where('otp_code',$input['otp_code'])->get();
        if(count($user) == 1){
            $user = Admin::where('id',$id)->where('otp_code',$input['otp_code'])->update(['is_otp_verified' => '1']);
        } else {
            return redirect()->back()->with('danger', 'Failed! Otp not matched.');
        }


        return redirect(route('admin.staff.index', $role))->with('success', 'Success! New record has been added.');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\planplanplan  $plan
     * @return \Illuminate\Http\Response
     */
    public function show(PlanCondition $plan)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\planplan  $plan
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $role, $staff)
    {
        $staff = Admin::find($staff);
        $editData =  ['record' => $staff->toArray()];
        $request->replace($editData);
        $request->flash();

        $data = compact('staff', 'role');
        // dd($data);
        return view('backend.inc.staff.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\plan  $plan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $role, $staff)
    {
        $rules = [
            'record'        => 'required|array',
            'record.fname'   => 'required|string',
            'record.mobile'  => 'required|unique:admins,mobile,' . $staff,
        ];

        $messages = [
            'record.name'  => 'Please Enter Name.',
            'image'  => 'Please Select Image'
        ];
        $request->validate($rules, $messages);

        $staff = Admin::find($staff);
        
        $record     = $staff;
        $input      = $request->record;
        if ($input['password']) {
            $input['password']    = Hash::make($input['password']);
        }
        if ($request->hasFile('aadhar_front')) {
            $file = $request->aadhar_front;
            $optimizeImage = Image::make($file);
            // $optimizeImage->resize(1903, 523);
            $optimizePath = public_path() . '/images/admin/aadhar/';
            $name = time() . $file->getClientOriginalName();
            $optimizeImage->save($optimizePath . $name, 72);
            $input['aadhar_front'] = $name;
        }
        if ($request->hasFile('aadhar_back')) {
            $file = $request->aadhar_back;
            $optimizeImage = Image::make($file);
            // $optimizeImage->resize(1903, 523);
            $optimizePath = public_path() . '/images/admin/aadhar/';
            $name = time() . $file->getClientOriginalName();
            $optimizeImage->save($optimizePath . $name, 72);
            $input['aadhar_back'] = $name;
        }
        if ($request->hasFile('pan_img')) {
            $file = $request->pan_img;
            $optimizeImage = Image::make($file);
            // $optimizeImage->resize(1903, 523);
            $optimizePath = public_path() . '/images/admin/pan_card/';
            $name = time() . $file->getClientOriginalName();
            $optimizeImage->save($optimizePath . $name, 72);
            $input['pan_img'] = $name;
        }
        if ($request->hasFile('bank_statement')) {
            $file = $request->bank_statement;

resources/views/backend/inc/staff/add.blade.php
@extends('backend.layout.master')
@section('title', $role)
@section('content')
<div class="main-content box">
    <main class="main-i">
        <div class="container-fluid">
            <h3 class="mt-4 titl-fo">Add {{ $role }}</h3>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item active"><a href="{{ route('admin.home') }}">Dashboard</a></li>
                <li class="breadcrumb-item active"><a href="{{ route('admin.staff.index',$role) }}">{{ $role }}</a></li>
                <li class="breadcrumb-item active">Add {{ $role }}</li>
            </ol>
            <div class="main-addpage-main">
                <div class="main-form-deco">
                    {{ Form::open(['url' => route('admin.staff.store',$role), 'method'=>'POST', 'files' => true, 'class' => 'user']) }}
                    @include('backend.inc.staff._form')
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                            {{Form::label('aadhar_front', 'Choose aadhar front image'), ['class' => 'active']}}
                            {{Form::file('aadhar_front',['class'=>'form-control'])}}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                            {{Form::label('aadhar_back', 'Choose aadhar back image'), ['class' => 'active']}}
                            {{Form::file('aadhar_back',['class'=>'form-control'])}}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                            {{Form::label('pan_img', 'Choose pan image'), ['class' => 'active']}}
                            {{Form::file('pan_img',['class'=>'form-control'])}}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                            {{Form::label('bank_statement', 'Choose Cancel Cheque OR Passbook Image'), ['class' => 'active']}}
                            {{Form::file('bank_statement',['class'=>'form-control'])}}
                            </div>
                        </div>
                    </div>
                    <div class="text-right mt-4">
                        <input type="submit" class="btn btn-primary" name="save" value="Add" />
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </main>
</div>
@endsection

resources/views/backend/inc/staff/list.blade.php
@extends('backend.layout.master')
@section('title', $role)
@section('content')
<div class="main-content box">
    <main class="main-i">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6">
                    <h3 class="mt-4 titl-fo">View {{ $role }}</h3>
                    <ol class="breadcrumb mb-4">
                        <li class="breadcrumb-item active"><a href="{{ route('admin.home') }}">Dashboard</a></li>
                        <li class="breadcrumb-item active">{{ $role }}</li>
                    </ol>
                </div>
                @if(auth()->user()->role_id != 1)
                <div class="col-lg-6">
                    <div class="buton-add-new">
                        <a href="{{ route('admin.staff.create',$role) }}" class="btn btn-primary" type="button"><i class='bx bx-plus'>Add</i></a>
                    </div>
                </div>
                @endif
            </div>
            <section class="recent">
                <div class="activiti-card">
                    <!-- <div class="search-top-table">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="searchbarleft">
                                    <input type="text" class="search-input-table" name="Search" placeholder="Search-Filter">
                                </div>
                                <h4>View staff</h4>
                            </div>
                            <div class="col-lg-6">
                                <div class="table-head-right">
                                    <button type="button"><i class='bx bxs-trash'></i></button>
                                </div>
                            </div>
                        </div>
                    </div> -->
                    <div class="table-responsiveima pt-4">
                    <input class="form-control mb-3" style="width:25%" id="myInput" type="text" placeholder="Search..">
                        <table>
                            <thead class="the-colo-table">
                                <tr>
                                    <!-- <th><input type="checkbox" name="sr.no">Sr.No</th> -->
                                    <th>S. No.</th>
                                    <th>Added By</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Mobile</th>
                                    <th>Pan Card</th>
                                    <th>Aadhar Card</th>
                                    <th>Bank Statement</th>
                                    <th>Bank Details</th>
                                    <th>Address</th>
                                    @if($role == 'Shop')
                                    <th>Shop Name</th>
                                    @endif
                                    @if(auth()->user()->id == 1)
                                    <th>Action</th>
                                    @endif
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody id="myTable">
                                @php
                                $sn = 1;
                                @endphp
                                @foreach($lists as $list)
                                <tr>
                                    <td>{{ $sn++ }}</td>
                                    <td>
                                        {{ $list->admin ? $list->admin->fname : 'N/A' }} <br>
                                        <small> ({{ $list->admin ? $list->admin->role->name : 'N/A' }}) </small>
                                    </td>
                                    <td>
                                    @if(auth()->user()->role_id != 1 )
                                    <a href="{{ route('admin.staff.edit',[$role,$list->id]) }}"><i class=" bx bxs-edit"></i> {{ $list->fname }} {{ $list->lname }}</a>
                                    @else 
                                    @if($list->role->name == 'Franchise')
                                    <a href="{{ route('admin.staff.edit',[$role,$list->id]) }}"><i class=" bx bxs-edit"></i> {{ $list->fname }} {{ $list->lname }}</a>
                                    @else
                                    {{ $list->fname }} {{ $list->lname }}
                                    @endif
                                    @endif
                                    </td>
                                    <td>{{ $list->email }} </td>
                                    <td>
                                        @if($list->alternative_mobile_no) <span style="font-weight:550">Mobile No. -</span>  {{$list->alternative_mobile_no}} @endif <br>
                                        @if($list->mobile) <span style="font-weight:550">Mobile No. -</span>  {{$list->mobile}} @endif <br>
                                        @if($list->alternative_whatsapp_no) <span style="font-weight:550">Whatsapp No. -</span>  {{$list->alternative_whatsapp_no}} @endif 
                                    </td>
                                    <td>
                                    <span style="font-weight:bold">{{ $list->pancard ?  $list->pancard : 'N/A' }}</span> <br>
                                    @if($list->pan_img)
                                        <a href="{{ url('/images/admin/pan_card/'.$list->pan_img) }}" target="_blank">
                                            <img src="{{ url('/images/admin/pan_card/'.$list->pan_img) }}" alt="" width="100px" class="table_img">
                                        </a>
                                    @endif  
                                    </td>
                                    <td>
                                        <!-- {{ $list->aadharcard  ? $list->aadharcard : 'N/A' }} -->
                                        <span style="font-weight:bold">{{ $list->aadharcard  ?  $list->aadharcard : 'N/A' }} </span><br>
                                        @if($list->aadhar_front)
                                        <a href="{{ url('/images/admin/aadhar/'.$list->aadhar_front) }}" target="_blank" >
                                            <img src="{{ url('/images/admin/aadhar/'.$list->aadhar_front) }}" alt="" width="60px" class="table_img">
                                        </a>
                                        @endif
                                        @if($list->aadhar_back)
                                        <a href="{{ url('/images/admin/aadhar/'.$list->aadhar_back) }}" target="_blank">
                                            <img src="{{ url('/images/admin/aadhar/'.$list->aadhar_back) }}" alt="" width="60px" class="table_img">
                                        </a>
                                        @endif
                                    </td>
                                    <td>
                                        @if($list->bank_statement)
                                        <a href="{{ url('/images/admin/bank_statement/'.$list->bank_statement) }}" target="_blank">
                                            <img src="{{ url('/images/admin/bank_statement/'.$list->bank_statement) }}" alt="" width="100px" class="table_img">
                                        </a>
                                        @endif
                                    </td>
                                    <td> 
                                       <span style="font-weight:550"> {{ $list->bank_name }} {{ $list->branch_name }}</span> <br>
                                       @if($list->ifsc_code) <span style="font-weight:550">IFSC code -</span>  {{$list->ifsc_code}} @endif <br>
                                       @if($list->acc_holder) <span style="font-weight:550">Acc holder -</span>  {{$list->acc_holder}} @endif <br>
                                       @if($list->acc_no) <span style="font-weight:550">Acc No. -</span>  {{$list->acc_no}} @endif
                                    </td>
                                    <td>{{ $list->address }} @if($list->address),@endif {{ $list->city }}@if($list->city),@endif {{ $list->state }}@if($list->state),@endif {{ $list->pincode }}</td>
                                    @if($role == 'Shop')
                                    <td>{{ $list->shop_name }}</td>
                                    @endif
                                    @if(auth()->user()->id == 1)
                                    <td>
                                        <!-- <button class="btn tblActnBtn p-0">
                                            <a href="{{ route('admin.staff.edit',[$role,$list->id]) }}" style="color: black;"><i class="bx bxs-edit"></i></a>
                                        </button> -->
                                        {{ Form::open(array('url' => route('admin.staff.destroy',$list->id), 'class' => 'btn tblActnBtn','style'=> 'padding:0px;')) }}
                                        {{ Form::hidden('_method', 'POST') }}
                                        <button class="btn tblActnBtn">
                                            <a style="color: black;"><i class="bx bxs-trash"></i></a>
                                        </button>
                                        {{ Form::close() }}
                                    </td>
                                    @endif
                                    @php
                                    $statusArr = [
                                    'true' => 'Active',
                                    'false' => 'Inactive',
                                    ]
                                    @endphp
                                    <td>
                                        {{ Form::select('verified', $statusArr,$list->active, ['class'=>'form-control','id'=>url('/admin-access/staff/status/'.$list->id), 'onchange'=>'myFunction(this)']) }}
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="p-3 text-right">{{ $lists->links() }}</div>
                </div>
            </section>
        </div>
    </main>
</div>
<script>
    function myFunction(abc) {
        window.location = abc.id + '/' + abc.value;
    }
</script>
@endsection