routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'guest:admin', 'namespace' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/login', 'LoginController@index')->name('login');
    Route::post('/checklogin', 'LoginController@checklogin')->name('checklogin');

    Route::get('/forgot_password_step-1', 'LoginController@forgotPasswordstep_i_get');
    Route::post('/forgot_password_step-1', 'LoginController@forgotPasswordstep_i')->name('admin-forgot.step-1');
    Route::get('/forgot_password_step-2', 'LoginController@forgotPasswordstep_ii_get');
    Route::get('/forgot_password_step-2/resend_otp', 'LoginController@forgot_resend_otp');
    Route::post('/forgot_password_step-2', 'LoginController@forgotPasswordstep_ii')->name('admin-forgot.step-2');
    Route::get('/otp_verify', 'LoginController@otp_verify_get');
    Route::post('/otp_verify-2', 'LoginController@otp_verify_post')->name('otp-verify');
});

Route::group(['middleware' => 'auth:admin', 'namespace' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/', 'DashboardController@index')->name('home');
    Route::get('/logout', 'LoginController@logout')->name('logout');

    Route::get('/page', 'PageController@index')->name('page.index');
    Route::get('/page/edit/{id}', 'PageController@edit')->name('page.edit');
    Route::post('/page/edit/{id}', 'PageController@update')->name('page.update');

    Route::get('/setting', 'SettingController@edit')->name('setting.edit');
    Route::post('/setting', 'SettingController@update')->name('setting.update');

    Route::get('/change-password', 'LoginController@change_password')->name('user.edit');
    Route::post('/change-password', 'LoginController@save_password')->name('user.update');

    Route::post('/inquery/{id}', 'DashboardController@destroy')->name('inquery_delete');

    Route::get('/plan/{plan}/rule', 'PlanRuleController@index')->name('planrule.index');
    Route::get('/plan/{plan}/ruleadd', 'PlanRuleController@create')->name('planrule.create');
    Route::post('/plan/{plan}/ruleadd', 'PlanRuleController@store')->name('planrule.store');
    Route::get('/plan/{plan}/ruleedit/{id}', 'PlanRuleController@edit')->name('planrule.edit');
    Route::post('/plan/{plan}/ruleedit/{id}', 'PlanRuleController@update')->name('planrule.update');
    Route::post('/plan/ruledelete/{id}', 'PlanRuleController@destroy')->name('planrule.destroy');

    Route::get('/staff/{role}', 'StaffController@index')->name('staff.index');
    Route::get('/staff/{role}/add', 'StaffController@create')->name('staff.create');
    Route::post('/staff/{role}/add', 'StaffController@store')->name('staff.store');
    Route::get('/staff/{role}/verify/{id}', 'StaffController@otp_verify_get')->name('staff.verify');
    Route::post('/staff/{role}/verify/{id}', 'StaffController@otp_verify_post')->name('staff.verify_post');
    Route::get('/staff/{role}/edit/{id}', 'StaffController@edit')->name('staff.edit');
    Route::post('/staff/{role}/edit/{id}', 'StaffController@update')->name('staff.update');
    Route::post('/staff/delete/{id}', 'StaffController@destroy')->name('staff.destroy');
    Route::get('/staff/status/{id}/{status}', 'StaffController@status')->name('staff.status');

    Route::get('/insurance', 'InsuranceController@index')->name('insurance.index');
    Route::get('/insurance/resend_otp', 'InsuranceController@resend_otp');
    Route::get('/insurance/add', 'InsuranceController@create')->name('insurance.create');
    Route::get('/insurance/filter_plan', 'InsuranceController@filter_plan')->name('insurance.filter_plan');    
    Route::get('/insurance/{id}', 'InsuranceController@insurance_detail');
    
    Route::post('/insurance/add', 'InsuranceController@store')->name('insurance.store');
    Route::resources([
        'faq' => 'FaqController',
        'slider' => 'SliderController',
        'brand' => 'BrandController',
        'plan' => 'PlanController',
        'smartphone' => 'MobileController',
        'howitwork' => 'HowitworkController',
        'service' => 'ServiceController',
        'testimonial' => 'TestimonialController',
    ]);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('', 'HomeController@home');
Route::get('contact', 'HomeController@contact');

Route::get('faq', 'HomeController@faq');
Route::get('service', 'HomeController@service');
Route::any('plan', 'PlanController@index')->name('plan');
Route::post('inquery', 'InqueryController@store')->name('inquiry');

Route::get('login', 'AuthController@loginget');
Route::post('login', 'AuthController@loginpost')->name('login');
Route::get('logout', 'AuthController@logout');

Route::get('register', 'AuthController@registerget');
Route::post('register', 'AuthController@registerpost')->name('register');

Route::get('register/otp_verify', 'AuthController@verify_otp');
Route::post('register/otp_verify', 'AuthController@verify_otp_post')->name('otp-verify');
Route::get('register/resend_otp', 'AuthController@resend_otp');

Route::get('profile', 'ProfileController@profile');
Route::post('user-update', 'ProfileController@update')->name('user.update');
Route::post('changepassword', 'ProfileController@changepassword')->name('user.changepassword');
Route::post('service_plan', 'InsuranceController@insurance_re')->name('insurance_re');
Route::get('service_plan/{id}', 'InsuranceController@create')->name('insurance.add');
Route::post('service_plan/{id}', 'InsuranceController@store')->name('insurance.store');
Route::get('page/{slug:slug}', 'HomeController@about');

Route::get('/forgot_password_step-1', 'AuthController@forgotPasswordstep_i_get');
Route::post('/forgot_password_step-1', 'AuthController@forgotPasswordstep_i')->name('forgot.step-1');
Route::get('/forgot_password_step-2', 'AuthController@forgotPasswordstep_ii_get');
Route::post('/forgot_password_step-2', 'AuthController@forgotPasswordstep_ii')->name('forgot.step-2');

resources/views/backend/common/footer.blade.php
</body>
</html>

resources/views/backend/common/header.blade.php
<header class="header " id="header">
	<div class="heder-dark">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-2 col-5">
					<div class="title-logo">APR<span> Service</span>
					</div>
				</div>
				<div class="col-lg-2 col-2">
					<div class="sidebar-btn">
						<div class=" mob-s-y change" id="button-enlarge"></i>
							<div class="bars"></div>
							<div class="bars"></div>
							<div class="bars"></div>
						</div>
					</div>
				</div>
				<div class="col-lg-8 col-5">
					<div class="navbar-icon-heder">
						<ul>
							<li class="nav-item dropdown hover-colo ">

								<a class="dropdown-toggle nav-my-co " href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> <i class='bx bxs-user' data-bs-toggle="tooltip" data-bs-placement="bottom" title="Profile"></i>
								</a>

								<ul class="dropdown-menu drop-hover-i" aria-labelledby="navbarDropdown">

									@if(auth()->user()->role_id == 1)
									<li><a class="dropdown-item" href="{{ route('admin.setting.edit') }}">Settings</a>
									</li>
									<li>
										<hr class="dropdown-divider">
									</li>
									@endif
									<li><a class="dropdown-item" href="{{ route('admin.user.edit') }}">Change Password</a>
									</li>
									<li>
										<hr class="dropdown-divider">
									</li>
									<li><a class="dropdown-item" href="{{ route('admin.logout') }}">Logout</a>
									</li>
								</ul>
							</li>
						</ul>
					</div>
					<!-- <div class="navbar-icon-heder2">
						<ul>
							<li class="nav-item dropdown hover-colo">
								<a class=" nav-my-co" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> <i class='bx bxs-bell' data-bs-toggle="tooltip" data-bs-placement="bottom" title="notification"></i>
								</a>
								<ul class="dropdown-menu  drop-hover-i" aria-labelledby="navbarDropdown">
									<li><a class="dropdown-item" href="#">Action</a>
									</li>
									<li><a class="dropdown-item" href="#">Another action</a>
									</li>
									<li>
										<hr class="dropdown-divider">
									</li>
									<li><a class="dropdown-item" href="#">Something else here</a>
									</li>
								</ul>
							</li>
						</ul>
					</div> -->
				</div>
			</div>
		</div>
	</div>
</header>

resources/views/backend/common/sidebar.blade.php
<div class="overly-main"></div>
<div class="sidebar mobileview">
  <!-- sidebar -->
  <div class="l-navbar sho" id="nav-bar">
    <nav class="navor mynave-listt">
      <div class="accordion">
        <ul>
          <li>
            <div class="main-deshbord-heding"> <span class="bx bxs-dashboard nav-icon" data-bs-toggle="tooltip" data-bs-placement="right"></span>
              <a href="{{ route('admin.home') }}" class="nav-text">Dashboard</a>
            </div>
          </li>
          @if(auth()->user()->role_id == 1)
          <li class="has-dropdown accordion-box ">
            <div class="drop-submenu-r"> <span class="bx bx-grid-alt nav-icon" data-bs-toggle="tooltip" data-bs-placement="right"></span>
              <span class="nav-text">Master</span>
              <a href=""></a>
            </div>
            <div class="accordion-content">
              <ul>
                <li class="has-dropdown accordion-box">
                  <div class="drop-submenu-r"> <span class="nav-text" style="margin-left: 25px;">Slider</span>
                    <a href=""></a>
                  </div>
                  <div class="accordion-content">
                    <ul style="margin-left: 25px;">
                      <li> <a href="{{ route('admin.slider.create') }}">Add</a></li>
                      <li> <a href="{{ route('admin.slider.index') }}">View</a></li>
                    </ul>
                  </div>
                </li>
                <li class="has-dropdown accordion-box">
                  <div class="drop-submenu-r"> <span class="nav-text" style="margin-left: 25px;">Brand</span>
                    <a href=""></a>
                  </div>
                  <div class="accordion-content">
                    <ul style="margin-left: 25px;">
                      <li> <a href="{{ route('admin.brand.create') }}">Add</a></li>
                      <li> <a href="{{ route('admin.brand.index') }}">View</a></li>
                    </ul>
                  </div>
                </li>
                <li class="has-dropdown accordion-box">
                  <div class="drop-submenu-r"> <span class="nav-text" style="margin-left: 25px;">Faqs</span>
                    <a href=""></a>
                  </div>
                  <div class="accordion-content">
                    <ul style="margin-left: 25px;">
                      <li> <a href="{{ route('admin.faq.create') }}">Add</a></li>
                      <li> <a href="{{ route('admin.faq.index') }}">View</a></li>
                    </ul>
                  </div>
                </li>
                <li class="has-dropdown accordion-box">
                  <div class="drop-submenu-r"> <span class="nav-text" style="margin-left: 25px;">How It Work</span>
                    <a href=""></a>
                  </div>
                  <div class="accordion-content">
                    <ul style="margin-left: 25px;">
                      <li> <a href="{{ route('admin.howitwork.create') }}">Add</a></li>
                      <li> <a href="{{ route('admin.howitwork.index') }}">View</a></li>
                    </ul>
                  </div>
                </li>
                <li class="has-dropdown accordion-box">
                  <div class="drop-submenu-r"> <span class="nav-text" style="margin-left: 25px;">Service</span>
                    <a href=""></a>
                  </div>
                  <div class="accordion-content">
                    <ul style="margin-left: 25px;">
                      <li> <a href="{{ route('admin.service.create') }}">Add</a></li>
                      <li> <a href="{{ route('admin.service.index') }}">View</a></li>
                    </ul>
                  </div>
                </li>
                <li class="has-dropdown accordion-box">
                  <div class="drop-submenu-r"> <span class="nav-text" style="margin-left: 25px;">Testimonial</span>
                    <a href=""></a>
                  </div>
                  <div class="accordion-content">
                    <ul style="margin-left: 25px;">
                      <li> <a href="{{ route('admin.testimonial.create') }}">Add</a></li>
                      <li> <a href="{{ route('admin.testimonial.index') }}">View</a></li>
                    </ul>
                  </div>
                </li>
                <li class="has-dropdown accordion-box">
                  <div class="drop-submenu-r"> <span class="nav-text" style="margin-left: 25px;">Smart Phone</span>
                    <a href=""></a>
                  </div>
                  <div class="accordion-content">
                    <ul style="margin-left: 25px;">
                      <li> <a href="{{ route('admin.smartphone.create') }}">Add</a></li>
                      <li> <a href="{{ route('admin.smartphone.index') }}">View</a></li>
                    </ul>
                  </div>
                </li>
              </ul>
            </div>
          </li>
          <li class="has-dropdown accordion-box">
            <div class="drop-submenu-r"> <span class="bx bx-grid-alt nav-icon" data-bs-toggle="tooltip" data-bs-placement="right">
              </span>
              <span class="nav-text">Plan</span>
              <a href=""></a>
            </div>
            <div class="accordion-content">
              <ul>
                <li> <a href="{{ route('admin.plan.create') }}">Add</a>
                <li> <a href="{{ route('admin.plan.index') }}">View</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="has-dropdown accordion-box">
            <div class="drop-submenu-r"> <span class="bx bx-grid-alt nav-icon" data-bs-toggle="tooltip" data-bs-placement="right">
              </span>
              <span class="nav-text">Franchise</span>
              <a href=""></a>
            </div>
            <div class="accordion-content">
              <ul>
                <li> <a href="{{ route('admin.staff.create','Franchise') }}">Add</a>
                <li> <a href="{{ route('admin.staff.index','Franchise') }}">View</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="accordion-box">
            <a href="{{ route('admin.staff.index','Shop') }}">
              <div class="drop-submenu-r"> <span class="bx bx-grid-alt nav-icon" style="width: 20px;" data-bs-toggle="tooltip" data-bs-placement="right">
                </span>
                <span class="nav-text" style="font-size: 16px;">Shop</span>
              </div>
            </a>
          </li>
          @endif
          @if(auth()->user()->role_id == 2 )
          <li class="has-dropdown accordion-box">
            <div class="drop-submenu-r"> <span class="bx bx-grid-alt nav-icon" data-bs-toggle="tooltip" data-bs-placement="right">
              </span>
              <span class="nav-text">Staff</span>
              <a href=""></a>
            </div>
            <div class="accordion-content">
              <ul>
                <li> <a href="{{ route('admin.staff.create','Staff') }}">Add</a>
                <li> <a href="{{ route('admin.staff.index','Staff') }}">View</a>
                </li>
              </ul>
            </div>
          </li>
          <li class="has-dropdown accordion-box">
            <div class="drop-submenu-r"> <span class="bx bx-grid-alt nav-icon" data-bs-toggle="tooltip" data-bs-placement="right">
              </span>
              <span class="nav-text">Shop</span>
              <a href=""></a>
            </div>
            <div class="accordion-content">
              <ul>
                <li> <a href="{{ route('admin.staff.create','Shop') }}">Add</a>
                <li> <a href="{{ route('admin.staff.index','Shop') }}">View</a>
                </li>
              </ul>
            </div>
          </li>
          @endif
          @if(auth()->user()->role_id == 5)
          <li class="has-dropdown accordion-box">
            <div class="drop-submenu-r"> <span class="bx bx-grid-alt nav-icon" data-bs-toggle="tooltip" data-bs-placement="right">
              </span>
              <span class="nav-text">Shop</span>
              <a href=""></a>
            </div>
            <div class="accordion-content">
              <ul>
                <li> <a href="{{ route('admin.staff.create','Shop') }}">Add</a>
                <li> <a href="{{ route('admin.staff.index','Shop') }}">View</a>
                </li>
              </ul>
            </div>
          </li>
          @endif
          @if(auth()->user()->role_id == 1)
          <li class="accordion-box">
            <a href="{{ route('admin.page.index') }}">
              <div class="drop-submenu-r"> <span class="bx bx-grid-alt nav-icon" style="width: 20px;" data-bs-toggle="tooltip" data-bs-placement="right">
                </span>
                <span class="nav-text" style="font-size: 16px;">Pages</span>
              </div>
            </a>
          </li>
          @endif
          @if(auth()->user()->role_id == 1)
          <li class="accordion-box">
            <a href="{{ route('admin.insurance.index') }}">
              <div class="drop-submenu-r"> <span class="bx bx-grid-alt nav-icon" style="width: 20px;" data-bs-toggle="tooltip" data-bs-placement="right">
                </span>
                <span class="nav-text" style="font-size: 16px;">Mobile Repair Services</span>
              </div>
            </a>
          </li>
          @else
            <li class="has-dropdown accordion-box">
              <div class="drop-submenu-r"> <span class="bx bx-grid-alt nav-icon" data-bs-toggle="tooltip" data-bs-placement="right">
                </span>
                <span class="nav-text">Mobile Repair Service</span>
                <a href=""></a>
              </div>
              <div class="accordion-content">
                <ul>
                  <li> <a href="{{ route('admin.insurance.create') }}">Add</a>
                  <li> <a href="{{ route('admin.insurance.index') }}">View</a>
                  </li>
                </ul>
              </div>
            </li>
          @endif
          @if(auth()->user()->role_id == 1)
          <li class="accordion-box">
            <a href="{{ route('admin.setting.edit') }}">
              <div class="drop-submenu-r"> <span class="bx bx-cog nav-icon" style="width: 20px;" data-bs-toggle="tooltip" data-bs-placement="right">
                </span>
                <span class="nav-text" style="font-size: 16px;">Setting</span>
              </div>
            </a>
          </li>
          @endif
          <li class="accordion-box">
            <a href="{{ route('admin.user.edit') }}">
              <div class="drop-submenu-r"> <span class="bx bx-grid-alt nav-icon" style="width: 20px;" data-bs-toggle="tooltip" data-bs-placement="right">
                </span>
                <span class="nav-text" style="font-size: 16px;">Change Password</span>
              </div>
            </a>
          </li>
          <li class="accordion-box">
            <a href="{{ route('admin.logout') }}">
              <div class="drop-submenu-r"> <span class="bx bx-grid-alt nav-icon" style="width: 20px;" data-bs-toggle="tooltip" data-bs-placement="right">
                </span>
                <span class="nav-text" style="font-size: 16px;">LogOut</span>
              </div>
            </a>
          </li>
        </ul>
      </div>
    </nav>
  </div>
  <!-- sidbar -->
</div>